import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, CheckCircle2, Clock3, Eye, EyeOff, Plus, RefreshCw, Target} from 'lucide-react';
import './styles.css';
import './responsive.css';
const API='http://127.0.0.1:8000/api';
type Capture={id:number;created_at:string;app_name:string;window_title:string;category:string;image_path?:string;task_summary?:string;next_action?:string;ai_status:string;ocr_text:string};
async function api(path:string, options?:RequestInit){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...options}); if(!r.ok) throw new Error(await r.text()); return r.json()}
function App(){
 const [settings,setSettings]=useState<any>({privacy_enabled:'false',capture_interval:'20'}); const [brief,setBrief]=useState<any>(null); const [captures,setCaptures]=useState<Capture[]>([]); const [goals,setGoals]=useState<any[]>([]); const [analytics,setAnalytics]=useState<any>({}); const [goal,setGoal]=useState(''); const [tab,setTab]=useState<'home'|'history'|'goals'|'settings'>('home'); const [error,setError]=useState('');
 const load=async()=>{try{const [s,b,c,g,a]=await Promise.all([api('/settings'),api('/resume-brief'),api('/captures'),api('/goals'),api('/analytics/daily')]);setSettings(s);setBrief(b);setCaptures(c);setGoals(g);setAnalytics(a);setError('')}catch{setError('Backend unavailable. Start FastAPI on port 8000.')}};
 useEffect(()=>{load();const timer=window.setInterval(load,20000);return()=>window.clearInterval(timer)},[]);
 const privacy=async()=>{const updated=await api('/settings',{method:'PUT',body:JSON.stringify({privacy_enabled:settings.privacy_enabled!=='true'})});setSettings(updated)};
 const addGoal=async(e:React.FormEvent)=>{e.preventDefault();if(!goal.trim())return;await api('/goals',{method:'POST',body:JSON.stringify({title:goal})});setGoal('');load()};
 const toggleGoal=async(id:number)=>{await api(`/goals/${id}/complete`,{method:'PATCH'});load()};
 return <main><aside><div className="brand"><Activity/> ReFocus</div><p>Return to what matters.</p>{(['home','history','goals','settings'] as const).map(x=><button className={tab===x?'nav active':'nav'} onClick={()=>setTab(x)} key={x}>{x}</button>)}<div className="privacy"><span>{settings.privacy_enabled==='true'?<Eye/>:<EyeOff/>}</span><div><b>Private capture</b><small>{settings.privacy_enabled==='true'?'On · local only':'Off by default'}</small></div><button className="switch" onClick={privacy}>{settings.privacy_enabled==='true'?'ON':'OFF'}</button></div></aside><section className="content">{error&&<div className="error">{error}</div>}<header><div><span className="eyebrow">YOUR FOCUS COMPANION</span><h1>{tab==='home'?'Welcome back.':tab[0].toUpperCase()+tab.slice(1)}</h1></div><div className="header-actions"><button className="mobile-privacy" onClick={privacy}>{settings.privacy_enabled==='true'?<Eye size={16}/>:<EyeOff size={16}/>}{settings.privacy_enabled==='true'?'Capture on':'Capture off'}</button><button className="icon" onClick={load}><RefreshCw size={18}/></button></div></header>{tab==='home'&&<Home brief={brief} analytics={analytics} captures={captures} onDelete={async(id:number)=>{await api(`/captures/${id}`,{method:'DELETE'});load()}}/>}{tab==='history'&&<History captures={captures}/>} {tab==='goals'&&<Goals goals={goals} goal={goal} setGoal={setGoal} addGoal={addGoal} toggle={toggleGoal}/>} {tab==='settings'&&<Settings settings={settings} save={async(v:any)=>{const s=await api('/settings',{method:'PUT',body:JSON.stringify(v)});setSettings(s)}}/>}</section></main>}
function Home({brief,analytics,captures,onDelete}:any){return <><div className="metrics"><Metric icon={<Clock3/>} label="Away today" value={`${analytics.away_minutes||0} min`}/><Metric icon={<Activity/>} label="Context captures" value={analytics.captures||0}/><Metric icon={<Target/>} label="Goals completed" value={`${analytics.goals_completed||0}/${analytics.goals_total||0}`}/></div><article className="brief"><div className="brief-head"><span className="badge">{brief?.available?'READY TO RESUME':'WAITING FOR CONTEXT'}</span><h2>{brief?.available?'Here’s where you left off':'Capture is private and off by default.'}</h2></div>{brief?.available?<><p>{brief.summary}</p><div className="next"><b>Suggested next step</b><span>{brief.next_action}</span></div><small>Source: {brief.capture.app_name} · {brief.capture.window_title || 'Untitled window'} · AI {brief.ai_status}</small></>:<p>Enable private capture, then run the companion agent. ReFocus keeps every screenshot and insight on this computer.</p>}</article><div className="section-title"><div><span className="eyebrow">CONTEXT TIMELINE</span><h2>Recent captures</h2></div></div><div className="timeline">{captures.map((c:Capture)=><article className="capture" key={c.id}>{c.image_path?<img src={`http://127.0.0.1:8000${c.image_path}`} />:<div className="placeholder">No image</div>}<div><span className="badge muted">{c.category}</span><h3>{c.window_title||c.app_name}</h3><p>{c.task_summary||c.ocr_text||'Processing context…'}</p><small>{new Date(c.created_at).toLocaleString()}</small></div><button className="delete" onClick={()=>onDelete(c.id)}>Remove</button></article>)}{!captures.length&&<div className="empty">Your private recovery timeline will appear here.</div>}</div></>}
function Metric({icon,label,value}:any){return <article className="metric"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>}
function History({captures}:any){return <><p className="lede">A local record of your recent work context.</p><div className="history">{captures.map((c:Capture)=><div key={c.id}><b>{c.category}</b><span>{c.app_name}</span><span>{c.window_title}</span><time>{new Date(c.created_at).toLocaleString()}</time></div>)}</div></>}
function Goals({goals,goal,setGoal,addGoal,toggle}:any){return <><p className="lede">Turn today’s intention into a clear finish line.</p><form onSubmit={addGoal}><input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Add a goal for today"/><button><Plus size={17}/> Add goal</button></form><div className="goals">{goals.map((g:any)=><button className={g.completed?'goal done':'goal'} onClick={()=>toggle(g.id)} key={g.id}><CheckCircle2/><span>{g.title}</span></button>)}{!goals.length&&<div className="empty">No goals yet—add the first one above.</div>}</div></>}
function Settings({settings,save}:any){const [interval,setInterval]=useState(settings.capture_interval||20);const [model,setModel]=useState(settings.ollama_model||'llama3.2');return <div className="settings"><label>Capture interval <input type="number" min="10" max="300" value={interval} onChange={e=>setInterval(e.target.value)}/><small>seconds</small></label><label>Ollama model <input value={model} onChange={e=>setModel(e.target.value)}/></label><button onClick={()=>save({capture_interval:Number(interval),ollama_model:model})}>Save local settings</button><p>Capture remains local. If Ollama is unavailable, ReFocus retains OCR context and shows a recovery fallback.</p></div>}
createRoot(document.getElementById('root')!).render(<App/>);
